### ISSUE TITLE
Color not working.

### ISSUE THREAD

**Issue by barry99705** [GaryFunk/Nanoleaf-Tiles#10]
When I try setting a solid color it just gives an exclamation mark.  Other buttons are working.  Nanoleaf shapes, firmware version 1.02.005.

**Comment by GaryFunk** [comment]
> When I try setting a solid color it just gives an exclamation mark. Other buttons are working. Nanoleaf shapes, firmware version 1.02.005.

What version are you using?

**Comment by barry99705** [comment]
1.1

**Comment by GaryFunk** [comment]
Download v1.2 and let me know if you have issues.

**Comment by barry99705** [comment]
That fixed it!  Thanks.

**Comment by GaryFunk** [comment]
Thank you for confirming it worked.
