### ISSUE TITLE
Discord invite not valid anymore

### ISSUE THREAD

**Issue by fharper** [GaryFunk/Nanoleaf-Tiles#15]
Discord invite in https://github.com/GaryFunk/Nanoleaf-Tiles/blob/main/README.md not valid anymore

<img width="481" alt="CleanShot 2022-02-15 at 17 08 37@2x" src="https://user-images.githubusercontent.com/1170989/154157826-3d80c67c-2e18-402c-9391-ea1818336999.png">

**Comment by oSPANNERo** [comment]
Same issue persists.

**Comment by GaryFunk** [comment]
This has been fixed.

**Comment by fharper** [comment]
@GaryFunk : there is a missing double quote in the URL btw

**Comment by GaryFunk** [comment]
Geez.  I
I'm normally not that careless.  I fixed it. 

@fharper How many Nanoleaf controllers do you have?

**Comment by fharper** [comment]
> I'm normally not that careless. I fixed it.
@GaryFunk : no stress, I just copied the link, and was on my phone so not able to do a PR.

> How many Nanoleaf controllers do you have?
Just one :)
