### ISSUE TITLE
Nanoleaf Essentials?

### ISSUE THREAD

**Issue by balupton** [GaryFunk/Nanoleaf-Tiles#6]
Does it work with the Nanoleaf lightbulb range? Aka essentials? Aka A19/B22
https://www.apple.com/au/shop/product/HPEL2B/A/nanoleaf-essentials-a19-b22

**Comment by GaryFunk** [comment]
It does not as Essentials is Bluetooth. I am looking for a Threaded Router that will allow for control over Ethernet.

**Comment by balupton** [comment]
Found this: https://nanoleaf.me/en-AU/products/nanoleaf-essentials/#specs-and-faqs

> It does not as Essentials is Bluetooth

I'm not sure what you mean, the page advertises they are Bluetooth and Thread - however perhaps the Thread network is an overlay over bluetooth, I personally don't know.

The page does mention this though:

> Essentials currently only supports Thread through iOS and do not work with other systems like Google Nest.

---

>  I am looking for a Threaded Router that will allow for control over Ethernet.

Page mentions this, perhaps it helps. Personally I have the Apple TV and  Eero option.

> Compatible Thread Border Routers ?
> Apple HomePod mini, Apple TV 4K (2nd generation), Nanoleaf Shapes Controller, Nanoleaf Elements Controller, Apple HomePod mini eero pro, eero beacon, eero Pro 6, eero 6

**Comment by DakSevkla** [comment]
The Nanoleaf Shapes Control Panel now acts as a Thread Border Router, and the Essentials upgraded to 1.6.8 firmware connect to the Nanoleaf Shapes Thread network so I have full thread connectivity to the Essentials.  I can group them and control them through the Nanoleaf Desktop App without issue.  This should be possible!  I might dig into it if you don't get a chance.
